[package]
name = "governance"
version = "0.18.4"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
norn-sdk = { path = "../../norn-sdk" }
borsh = { version = "1.5", default-features = false, features = ["derive"] }

[profile.release]
opt-level = "z"
lto = true
strip = true
